Add raw-content plugin, get raw embed description content
modmail-dev/Modmail pull request #3177
Opened 2022-08-24 00:01 UTC by Nzii3

2022-08-24 00:02 UTC, Nzii3 commented
For more context, you can’t copy embed description content on iOS unlike Android or other mobile devices.

2022-09-20 14:40 UTC, fourjr commented
Please update to v4 first.

2023-03-12 17:24 UTC, StephenDaDev commented
@Nzii3 Not sure if you still want to add this in or not

2023-03-12 17:44 UTC, Nzii3 commented
> Please update to v4 first.

Done

2023-03-12 17:44 UTC, Nzii3 commented
> @Nzii3 Not sure if you still want to add this in or not

Yeah I do.

2023-03-13 23:23 UTC, StephenDaDev requested changes

2023-03-13 23:23 UTC, StephenDaDev commented on plugins/registry.json
Did not provide a thumbnail or logo image, please provide something to keep consistency with every other plugin in the registry

2023-03-14 06:07 UTC, Taaku18 requested changes

2023-03-14 06:07 UTC, Taaku18 commented on plugins/registry.json
> +        "title": "Raw Content",
As mentioned by Stephen, it's preferred to include an icon and thumbnail (given by URL). Also, I don't believe you're allowed to end JSON objects with a trailing comma, that would probably trigger a parsing error.

2023-03-14 06:10 UTC, Taaku18 commented on plugins/registry.json
> +        "title": "Raw Content",
I've fixed the comma issue, but would still prefer to have the two images.

2023-03-14 13:52 UTC, Nzii3 commented
I don’t have a thumbnail for it

2023-03-14 20:08 UTC, Taaku18 commented
> I don’t have a thumbnail for it

Feel free to find one from the internet (preferably not copyrighted), or you can simply use the Modmail icon as some other plugins have done (https://i.imgur.com/Mo60CdK.png).

2023-07-04 02:59 UTC, StephenDaDev commented
@Nzii3 Please make these changes if you wish to proceed with this.

2023-07-11 07:18 UTC, closed without merging